actx_build.sh

modify actx_build.sh
--change prefix EOS-->ACTX, then change back

modify actx_build.sh

---

actx_build.sh

actx_build.sh

---

.gitignore
testnet.template

testnet.template

---

tutorials/bios-boot-tutorial/bios-boot-tutorial.py

get host ip  in tutorials/bios-boot-tutorial/bios-boot-tutorial.py
change localhost --> ip addr

get host ip 

---

programs/cleos/main.cpp

modify cli help infomation

---

plugins/net_plugin/net_plugin.cpp
plugins/producer_plugin/producer_plugin.cpp

modify actx default config

---

plugins/chain_plugin/chain_plugin.cpp

modify actx.token

---

contracts/actx.system/actx.system.cpp
contracts/actx.system/actx.system.hpp
contracts/actx.system/delegate_bandwidth.cpp
contracts/actx.system/voting.cpp
programs/cleos/main.cpp
unittests/bootseq_tests.cpp
unittests/eosio.system_tests.cpp
unittests/eosio_system_tester.hpp

optimize voting function -- drop the proxy

abandon vote proxy

---

plugins/mongo_db_plugin/mongo_db_plugin.cpp

comment consume thread

---

contracts/eosiolib/time.hpp
libraries/chain/include/eosio/chain/config.hpp

merge to master

---

plugins/net_plugin/include/eosio/net_plugin/protocol.hpp

correct the word

---

contracts/actx.system/delegate_bandwidth.cpp

delegatebw/undelegatebw no need to update votes

modify delegatebw

---

contracts/actx.system/producer_pay.cpp

use total_activated_stake as the denominator

modify claimrewards

---

contracts/actx.system/voting.cpp

unvote producer, remote the producer from the voter ' s producers

modify vote producer : remove votes = 0

---

programs/cleos/main.cpp

change wasm_file_not_found

---

contracts/actx.token/actx.token.abi
contracts/actx.token/actx.token.cpp
contracts/actx.token/actx.token.hpp
programs/cleos/main.cpp

add new CLI
add new attribute for statistics
extend to support multi-asset

add CLI to get account statistics

---

plugins/http_plugin/http_plugin.cpp

 fix the issue that the return of API get_block with nonexistent block NO.

---

contracts/actx.system/voting.cpp
contracts/eosiolib/privileged.h
libraries/chain/controller.cpp
libraries/chain/include/eosio/chain/config.hpp
libraries/chain/include/eosio/chain/controller.hpp
libraries/chain/include/eosio/chain/global_property_object.hpp
libraries/chain/include/eosio/chain/types.hpp
libraries/chain/wasm_interface.cpp

define schedule_size_type
add func uint32_t get_proposed_schedule_size()
modify system_contract::update_elected_producers
change initial_schedule_producer = 17

add parameter of schedule producers 's number

---

contracts/actx.system/actx.system.abi
contracts/actx.system/actx.system.cpp
contracts/actx.system/actx.system.hpp
contracts/eosiolib/privileged.h
libraries/chain/controller.cpp
libraries/chain/include/eosio/chain/controller.hpp
libraries/chain/wasm_interface.cpp
plugins/chain_plugin/chain_plugin.cpp
programs/cleos/main.cpp

set bp num
configini: init_bp_num

set bp num

---

libraries/chain/apply_context.cpp
libraries/chain/eosio_contract.cpp
libraries/chain/include/eosio/chain/types.hpp

update `shared_blob` data with api  `assign` instead of `resize`+`memcpy` 

---

plugins/net_plugin/net_plugin.cpp

 fix net_plugin dump issue

---

plugins/net_plugin/net_plugin.cpp

Reverts Achain-Dev/Achainplus#44

Revert " fix net_plugin dump issue"

---

plugins/net_plugin/net_plugin.cpp

use local logger to replace default logger so as to filter some logs

---

plugins/chain_plugin/include/eosio/chain_plugin/chain_plugin.hpp
programs/cleos/main.cpp

get_table_func add -t flag to set run time,default is 10 ms

get_table_func add -t flag

---

libraries/chain/controller.cpp

recover_keys before auth_check

recover_keys before auth_check

---

libraries/chain/wasm_interface.cpp

Limit assert message to 1024 chars

---

libraries/chain/block_log.cpp

Add logging to indicate hard replay progress

---

libraries/chain/CMakeLists.txt
libraries/chain/controller.cpp
libraries/chain/eosio_contract.cpp
libraries/chain/eosio_contract_abi.cpp
libraries/chain/include/eosio/chain/contract_types.hpp
libraries/chain/include/eosio/chain/controller.hpp
libraries/chain/include/eosio/chain/eosio_contract.hpp
libraries/chain/include/eosio/chain/set_config.hpp
libraries/chain/include/eosio/chain/types.hpp
libraries/chain/set_config.cpp
libraries/chain/wasm_interface.cpp
plugins/chain_api_plugin/chain_api_plugin.cpp
plugins/chain_plugin/chain_plugin.cpp
plugins/chain_plugin/include/eosio/chain_plugin/chain_plugin.hpp
programs/cleos/httpc.hpp
programs/cleos/main.cpp

set_chain_config/get_chain_config

---

libraries/chain/include/eosio/chain/set_config.hpp

delete some config

---

contracts/actx.system/actx.system.hpp
contracts/actx.system/voting.cpp
programs/cleos/main.cpp

CLI： system newaccount， supplay free ram for each new account

---

programs/cleos/main.cpp

print action traces in cleos even if nonmandatory fields are missing

print action traces in cleos even if nonmandatory fields are missing

---

CMakeLists.txt
Docker/config.ini

merge some fix

---

contracts/actx.system/actx.system.abi
contracts/actx.system/actx.system.cpp
contracts/actx.system/native.hpp
libraries/chain/controller.cpp
libraries/chain/include/eosio/chain/set_config.hpp

add chain config: f.nobid

---

programs/cleos/main.cpp

fix asset precision

---

programs/eosio-launcher/main.cpp

 Prevent core dump by catching exception while it was unable to parse last_run.json file

---

libraries/chain/controller.cpp

add startup logging for snapshots

---

Docker/genesis.json
tutorials/bios-boot-tutorial/genesis.json

modify genesis.json to fix default

---

libraries/chain/include/eosio/chain/config.hpp

change default BP num to 11

---

libraries/chain/transaction_context.cpp

fix assignment during timer creation

---

libraries/chain/transaction_context.cpp
plugins/producer_plugin/producer_plugin.cpp
unittests/main.cpp

merge update

---

libraries/chain/wasm_interface.cpp

fix wasm issue

---

scripts/helpers/eosio.sh

optimize download and replace "git.llvm.org" with "github.com/llvm-mirror"

replace "git.llvm.org" with "github.com/llvm-mirror"

---

plugins/http_plugin/http_plugin.cpp
plugins/http_plugin/include/eosio/http_plugin/http_plugin.hpp
plugins/http_plugin/include/eosio/http_plugin/local_endpoint.hpp
plugins/login_plugin/login_plugin.cpp
plugins/mongo_db_plugin/CMakeLists.txt
plugins/mongo_db_plugin/mongo_db_plugin.cpp
plugins/net_api_plugin/net_api_plugin.cpp
plugins/net_plugin/include/eosio/net_plugin/net_plugin.hpp
plugins/net_plugin/include/eosio/net_plugin/protocol.hpp
plugins/net_plugin/net_plugin.cpp

update merge plguin

---

plugins/state_history_plugin/include/eosio/state_history_plugin/state_history_log.hpp
plugins/state_history_plugin/include/eosio/state_history_plugin/state_history_plugin.hpp
plugins/state_history_plugin/include/eosio/state_history_plugin/state_history_serialization.hpp
plugins/state_history_plugin/state_history_plugin.cpp
plugins/state_history_plugin/state_history_plugin_abi.cpp
plugins/test_control_api_plugin/test_control_api_plugin.cpp
plugins/test_control_plugin/test_control_plugin.cpp

update state_history_plugin fix

---

libraries/builtins/README.txt
libraries/testing/CMakeLists.txt
libraries/testing/tester.cpp

update test file

---

libraries/testing/include/eosio/testing/tester.hpp
programs/keosd/main.cpp

update test fix

---

libraries/chain/include/eosio/chain/controller.hpp

update some merge

---

libraries/chain/eosio_contract.cpp

fix compile error

---

programs/nodeos/config.hpp.in

add node_executable_name

---

unittests/contracts/CMakeLists.txt

replace eosio with act

---

programs/cleos/main.cpp
programs/eosio-launcher/main.cpp
scripts/eosio_install.sh
scripts/eosio_uninstall.sh
unittests/forked_tests.cpp

change build script

---

CMakeLists.txt
CMakeModules/package.cmake
scripts/generate_rpm.sh
scripts/generate_tarball.sh
tests/Cluster.py
tests/get_table_tests.cpp

change rpm package script

---

plugins/chain_plugin/chain_plugin.cpp
plugins/chain_plugin/include/eosio/chain_plugin/chain_plugin.hpp
plugins/net_plugin/include/eosio/net_plugin/net_plugin.hpp
plugins/net_plugin/net_plugin.cpp
plugins/producer_plugin/producer_plugin.cpp
programs/cleos/main.cpp

fix crash issue and net sync issue

---

plugins/net_plugin/net_plugin.cpp

fix net sync issue
